# # TOKYODARK COLORS
# [colors.bright]
# # black = "#0c0d18"
# black = "#5f5f5f"
# blue = "#7199ee"
# cyan = "#f6955b"
# green = "#95c561"
# magenta = "#fe6D85"
# red = "#ee6d85"
# white = "#A0A8CD"
# yellow = "#d7a65f"
#
# [colors.normal]
# # black = "#0c0d18"
# black = "#2f2f2f"
# blue = "#648ce1"
# cyan = "#f6955b"
# green = "#98c379"
# magenta = "#fe6D85"
# red = "#ee6d85"
# white = "#A0A8CD"
# yellow = "#d7a65f"
#
# [colors.primary]
# background = "#11121D"
# foreground = "#A0A8CD"

# CUSTOM COLORS
[colors.bright]
black = "#333333"
red = "#FE6D85"
green = "#95C561"
yellow = "#A7C65F"
blue = "#648CE1"
magenta = "#A485DD"
cyan = "#A7D65F"
white = "#F0F0F0"

[colors.normal]
black = "#333333"
red = "#EE6D85"
green = "#608030"
yellow = "#A7C65F"
blue = "#648CE1"
magenta = "#A485DD"
cyan = "#A7D65F"
white = "#AAAAAA"

[colors.primary]
background = "#000000"
foreground = "#AAAAAA"

# LACKLUSTER COLORS
# [colors.primary]
# background = '#0A0A0A'
#
# [colors.normal]
# black = '#080808'
# red = '#ff7a93'
# green = '#789978'
# yellow = '#ffAA88'
# blue = '#7788AA'
# magenta = "#fe6D85"
# cyan = '#708090' 
# white = '#DEEEED'

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "Monaco"
style = "Medium"
